name: flutter_app_test1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+7

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  logarte: ^1.4.0
  shared_preferences: ^2.0.15 
  go_router: ^17.0.0
  get: ^4.7.2
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  firebase_core: ^4.2.1
  fluttertoast: ^9.0.0
  video_player: ^2.10.1
  toastification: ^3.0.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - shorebird.yaml
    - assets/video/
